/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    CodeHighLight: typeof import('./src/components/CodeHighLight.vue')['default']
    ContentDisplay: typeof import('./src/components/ContentDisplay.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    LoginOoutDialog: typeof import('./src/components/LoginOoutDialog.vue')['default']
    LoginOutDialog: typeof import('./src/components/LoginOutDialog.vue')['default']
    MarkdownFile: typeof import('./src/components/MarkdownFile.vue')['default']
    MarkdownRender: typeof import('./src/components/MarkdownRender.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    MarkdownView: typeof import('./src/components/MarkdownView.vue')['default']
    MarkdownViewer: typeof import('./src/components/MarkdownViewer.vue')['default']
    RemoveChatDialog: typeof import('./src/components/RemoveChatDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyEditor: typeof import('./src/components/TinyEditor.vue')['default']
    UserAddDialog: typeof import('./src/components/UserAddDialog.vue')['default']
    UserInfoDialog: typeof import('./src/components/UserInfoDialog.vue')['default']
  }
}
